//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomeInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IncomeInvoice()
        {
            this.IncomeInvoiceDetail = new HashSet<IncomeInvoiceDetail>();
        }
    
        public int Income_Invoice_ID { get; set; }
        public string Invoice_Number { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Supplier_ID { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncomeInvoiceDetail> IncomeInvoiceDetail { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
