//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomeInvoiceDetail
    {
        public int Income_Invoice_Detail_ID { get; set; }
        public int Income_Invoice_ID { get; set; }
        public int Product_ID { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
    
        public virtual IncomeInvoice IncomeInvoice { get; set; }
        public virtual Product Product { get; set; }
    }
}
