//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int Inventory_ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Responsible { get; set; }
        public string Results { get; set; }
        public Nullable<int> Warehouse_ID { get; set; }
    
        public virtual Warehouse Warehouse { get; set; }
    }
}
